#!/usr/bin/env bash
# A bash script that configures Nginx to redirect /redirect_me to another page with a 301 status

# Update package lists
sudo apt update
sudo apt install -y nginx

# Create a custom index.html page with the required content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to include the redirection
# sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
# Append the redirection directive to the default server block in the Nginx configuration file
sudo sed -i '/server {/a \\tlocation /redirect_me { return 301 http://www.davebryan.vercel.app/; }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart


